### ISSUE TITLE
TypeError: checker.for(...).exists is not a function

### ISSUE THREAD

**Issue by Turbo87** [billybonks/ember-cli-stylelint#93]
I got the following error after updating to v2.0.0:

```
TypeError: checker.for(...).exists is not a function
    at Class.init (/Users/tbieniek/Code/trainline/webapp/node_modules/ember-cli-stylelint/index.js:17:43)
    at Class.superWrapper [as init] (/Users/tbieniek/Code/trainline/webapp/node_modules/core-object/lib/assign-properties.js:34:20)
    at new CoreObject (/Users/tbieniek/Code/trainline/webapp/node_modules/core-object/core-object.js:9:15)
    at new Class (/Users/tbieniek/Code/trainline/webapp/node_modules/core-object/core-object.js:21:5)
    at new Class (/Users/tbieniek/Code/trainline/webapp/node_modules/core-object/core-object.js:21:5)
    at graph.each (/Users/tbieniek/Code/trainline/webapp/node_modules/ember-cli/lib/models/addons-factory.js:58:19)
    at Vertices.each (/Users/tbieniek/Code/trainline/webapp/node_modules/dag-map/dag-map.umd.js:197:13)
    at Vertices.walk (/Users/tbieniek/Code/trainline/webapp/node_modules/dag-map/dag-map.umd.js:125:14)
    at DAG.each (/Users/tbieniek/Code/trainline/webapp/node_modules/dag-map/dag-map.umd.js:68:24)
    at AddonsFactory.initializeAddons (/Users/tbieniek/Code/trainline/webapp/node_modules/ember-cli/lib/models/addons-factory.js:45:11)
```

**Comment by Turbo87** [comment]
looks like this is missing a `ember-cli-version-checker` dependency 🤔
